# Generated by Django 5.1.4 on 2025-01-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="Untitled Post", max_length=255),
        ),
    ]
