# Generated by Django 5.1.4 on 2025-01-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0004_profile_username_postreaction_delete_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(default="user.User", max_length=255),
        ),
    ]
