# Generated by Django 5.1.4 on 2025-01-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0005_alter_profile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(default="username", max_length=255),
        ),
    ]
