# Generated by Django 5.1.4 on 2025-01-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0006_alter_profile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
