# Generated by Django 5.1.4 on 2025-01-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0007_alter_profile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
