# Generated by Django 5.1.4 on 2025-01-06 03:32

import social_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0008_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=social_media.models.post_image_file_path,
            ),
        ),
        migrations.AlterField(
            model_name="postreaction",
            name="reaction",
            field=models.CharField(
                choices=[("Like", "Like"), ("Unlike", "Unlike")], max_length=10
            ),
        ),
    ]
