# Generated by Django 5.1.4 on 2025-01-06 05:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0009_alter_post_image_alter_postreaction_reaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="postreaction",
            unique_together={("user", "post")},
        ),
    ]
