# Generated by Django 5.1.4 on 2025-01-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0010_alter_postreaction_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="postreaction",
            unique_together=set(),
        ),
    ]
